get:
  operationId: configPoolValuesGet
  summary: Get an config pool value by ID
  tags:
    - Agents
  description: Retrieves details of a specific config pool value
  x-auth-permissions:
    - role: admin
      permission: always
  parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: "../components/schemas/common.yaml#/properties.UUID"
  responses:
    "200":
      description: Config pool value retrieved successfully
      content:
        application/json:
          schema:
            $ref: "../components/schemas/config_pool_values.yaml#/ConfigPoolValueRes"
    "401":
      $ref: "../components/responses.yaml#/Unauthorized"
    "403":
      $ref: "../components/responses.yaml#/Forbidden"
    "404":
      description: Config pool value not found
delete:
  operationId: configPoolValuesDelete
  summary: Delete an config pool value
  tags:
    - Agents
  description: Deletes an existing config pool value. Cannot delete a value that is currently allocated.
  x-auth-permissions:
    - role: admin
      permission: always
  parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: "../components/schemas/common.yaml#/properties.UUID"
  responses:
    "204":
      description: Config pool value deleted successfully
    "400":
      description: Cannot delete allocated pool value
    "401":
      $ref: "../components/responses.yaml#/Unauthorized"
    "403":
      $ref: "../components/responses.yaml#/Forbidden"
    "404":
      description: Config pool value not found
