get:
  operationId: configPoolsGet
  summary: Get an config pool by ID
  tags:
    - Agents
  description: Retrieves details of a specific config pool
  x-auth-permissions:
    - role: admin
      permission: always
    - role: agent
      permission: read-only
  parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: "../components/schemas/common.yaml#/properties.UUID"
  responses:
    "200":
      description: Config pool retrieved successfully
      content:
        application/json:
          schema:
            $ref: "../components/schemas/config_pools.yaml#/ConfigPoolRes"
    "401":
      $ref: "../components/responses.yaml#/Unauthorized"
    "403":
      $ref: "../components/responses.yaml#/Forbidden"
    "404":
      description: Config pool not found
patch:
  operationId: configPoolsUpdate
  summary: Update an config pool
  tags:
    - Agents
  description: Updates an existing config pool
  x-auth-permissions:
    - role: admin
      permission: always
  parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: "../components/schemas/common.yaml#/properties.UUID"
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/schemas/config_pools.yaml#/UpdateConfigPoolReq"
  responses:
    "200":
      description: Config pool updated successfully
      content:
        application/json:
          schema:
            $ref: "../components/schemas/config_pools.yaml#/ConfigPoolRes"
    "400":
      $ref: "../components/responses.yaml#/BadRequest"
    "401":
      $ref: "../components/responses.yaml#/Unauthorized"
    "403":
      $ref: "../components/responses.yaml#/Forbidden"
    "404":
      description: Config pool not found
delete:
  operationId: configPoolsDelete
  summary: Delete an config pool
  tags:
    - Agents
  description: Deletes an existing config pool
  x-auth-permissions:
    - role: admin
      permission: always
  parameters:
    - name: id
      in: path
      required: true
      schema:
        $ref: "../components/schemas/common.yaml#/properties.UUID"
  responses:
    "204":
      description: Config pool deleted successfully
    "401":
      $ref: "../components/responses.yaml#/Unauthorized"
    "403":
      $ref: "../components/responses.yaml#/Forbidden"
    "404":
      description: Config pool not found
