get:
  operationId: servicePoolValuesList
  summary: List service pool values
  tags:
    - Service Pools
  description: Retrieves a paginated list of service pool values with allocation status
  x-auth-permissions:
    - role: admin
      permission: all service pool values
    - role: participant
      permission: service pool values for its provider
    - role: agent
      permission: service pool values for its provider (read-only)
  parameters:
    - name: page
      in: query
      schema:
        type: integer
        default: 1
    - name: pageSize
      in: query
      schema:
        type: integer
        default: 20
    - name: servicePoolId
      in: query
      schema:
        $ref: "../components/schemas/common.yaml#/properties.UUID"
      description: Filter by service pool ID
    - name: serviceId
      in: query
      schema:
        $ref: "../components/schemas/common.yaml#/properties.UUID"
      description: Filter by allocated service ID
    - name: propertyName
      in: query
      schema:
        type: string
      description: Filter by property name
  responses:
    "200":
      description: A paginated list of service pool values
      content:
        application/json:
          schema:
            allOf:
              - $ref: "../components/schemas/common.yaml#/PageRes"
              - type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: "../components/schemas/service_pool_values.yaml#/ServicePoolValueRes"
    "401":
      $ref: "../components/responses.yaml#/Unauthorized"
    "403":
      $ref: "../components/responses.yaml#/Forbidden"
post:
  operationId: servicePoolValuesCreate
  summary: Create a service pool value
  tags:
    - Service Pools
  description: Creates a new service pool value (for list generators only)
  x-auth-permissions:
    - role: admin
      permission: always
    - role: participant
      permission: for its participant as provider
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/schemas/service_pool_values.yaml#/CreateServicePoolValueReq"
  responses:
    "201":
      description: Service pool value created successfully
      content:
        application/json:
          schema:
            $ref: "../components/schemas/service_pool_values.yaml#/ServicePoolValueRes"
    "400":
      $ref: "../components/responses.yaml#/BadRequest"
    "401":
      $ref: "../components/responses.yaml#/Unauthorized"
    "403":
      $ref: "../components/responses.yaml#/Forbidden"
