  get:
    operationId: servicesList
    summary: List services
    tags:
      - Services
    description: Retrieves a paginated list of services
    x-auth-permissions:
      - role: admin
        permission: all services
      - role: participant
        permission: services associated with its participant (as provider or consumer)
      - role: agent
        permission: services assigned to the agent
    parameters:
      - name: page
        in: query
        schema:
          type: integer
          default: 1
      - name: pageSize
        in: query
        schema:
          type: integer
          default: 20
    responses:
      "200":
        description: A paginated list of services
        content:
          application/json:
            schema:
              allOf:
                - $ref: "../components/schemas/common.yaml#/PageRes"
                - type: object
                  properties:
                    items:
                      type: array
                      items:
                        $ref: "../components/schemas/services.yaml#/ServiceRes"
      "401":
        $ref: "../components/responses.yaml#/Unauthorized"
      "403":
        $ref: "../components/responses.yaml#/Forbidden"
  post:
    operationId: servicesCreate
    summary: Create a service
    tags:
      - Services
    description: Creates a new service
    x-auth-permissions:
      - role: admin
        permission: always
      - role: participant
        permission: when acting as consumer
      - role: agent
        permission: not authorized
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../components/schemas/services.yaml#/ServiceReq"
    responses:
      "201":
        description: Service created successfully
        content:
          application/json:
            schema:
              $ref: "../components/schemas/services.yaml#/ServiceRes"
      "400":
        description: Invalid request or validation failed
        content:
          application/json:
            schema:
              oneOf:
                - $ref: "../components/schemas/common.yaml#/ErrorRes"
                - $ref: "../components/schemas/service_types.yaml#/ValidatePropertiesRes"
