/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentStatus } from './AgentStatus';
import {
    AgentStatusFromJSON,
    AgentStatusFromJSONTyped,
    AgentStatusToJSON,
    AgentStatusToJSONTyped,
} from './AgentStatus';
import type { AgentTypeRes } from './AgentTypeRes';
import {
    AgentTypeResFromJSON,
    AgentTypeResFromJSONTyped,
    AgentTypeResToJSON,
    AgentTypeResToJSONTyped,
} from './AgentTypeRes';
import type { TokenRes } from './TokenRes';
import {
    TokenResFromJSON,
    TokenResFromJSONTyped,
    TokenResToJSON,
    TokenResToJSONTyped,
} from './TokenRes';
import type { ParticipantRes } from './ParticipantRes';
import {
    ParticipantResFromJSON,
    ParticipantResFromJSONTyped,
    ParticipantResToJSON,
    ParticipantResToJSONTyped,
} from './ParticipantRes';

/**
 * 
 * @export
 * @interface AgentCreateRes
 */
export interface AgentCreateRes {
    /**
     * 
     * @type {string}
     * @memberof AgentCreateRes
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentCreateRes
     */
    name?: string;
    /**
     * 
     * @type {AgentStatus}
     * @memberof AgentCreateRes
     */
    status?: AgentStatus;
    /**
     * 
     * @type {string}
     * @memberof AgentCreateRes
     */
    providerId?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentCreateRes
     */
    agentTypeId?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof AgentCreateRes
     */
    tags?: Array<string>;
    /**
     * 
     * @type {ParticipantRes}
     * @memberof AgentCreateRes
     */
    participant?: ParticipantRes;
    /**
     * 
     * @type {AgentTypeRes}
     * @memberof AgentCreateRes
     */
    agentType?: AgentTypeRes;
    /**
     * 
     * @type {Date}
     * @memberof AgentCreateRes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof AgentCreateRes
     */
    updatedAt?: Date;
    /**
     * The agent authentication token
     * @type {TokenRes}
     * @memberof AgentCreateRes
     */
    token?: TokenRes;
}



/**
 * Check if a given object implements the AgentCreateRes interface.
 */
export function instanceOfAgentCreateRes(value: object): value is AgentCreateRes {
    return true;
}

export function AgentCreateResFromJSON(json: any): AgentCreateRes {
    return AgentCreateResFromJSONTyped(json, false);
}

export function AgentCreateResFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentCreateRes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : AgentStatusFromJSON(json['status']),
        'providerId': json['providerId'] == null ? undefined : json['providerId'],
        'agentTypeId': json['agentTypeId'] == null ? undefined : json['agentTypeId'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'participant': json['participant'] == null ? undefined : ParticipantResFromJSON(json['participant']),
        'agentType': json['agentType'] == null ? undefined : AgentTypeResFromJSON(json['agentType']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'token': json['token'] == null ? undefined : TokenResFromJSON(json['token']),
    };
}

export function AgentCreateResToJSON(json: any): AgentCreateRes {
    return AgentCreateResToJSONTyped(json, false);
}

export function AgentCreateResToJSONTyped(value?: AgentCreateRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': AgentStatusToJSON(value['status']),
        'providerId': value['providerId'],
        'agentTypeId': value['agentTypeId'],
        'tags': value['tags'],
        'participant': ParticipantResToJSON(value['participant']),
        'agentType': AgentTypeResToJSON(value['agentType']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'token': TokenResToJSON(value['token']),
    };
}

