/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum AgentStatus {
    NEW = 'New',
    CONNECTED = 'Connected',
    DISCONNECTED = 'Disconnected',
    ERROR = 'Error',
    DISABLED = 'Disabled'
}


export function instanceOfAgentStatus(value: any): boolean {
    for (const key in AgentStatus) {
        if (Object.prototype.hasOwnProperty.call(AgentStatus, key)) {
            if (AgentStatus[key as keyof typeof AgentStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AgentStatusFromJSON(json: any): AgentStatus {
    return AgentStatusFromJSONTyped(json, false);
}

export function AgentStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentStatus {
    return json as AgentStatus;
}

export function AgentStatusToJSON(value?: AgentStatus | null): any {
    return value as any;
}

export function AgentStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): AgentStatus {
    return value as AgentStatus;
}

