/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AgentTypeRes } from './AgentTypeRes';
import {
    AgentTypeResFromJSON,
    AgentTypeResFromJSONTyped,
    AgentTypeResToJSON,
    AgentTypeResToJSONTyped,
} from './AgentTypeRes';

/**
 * 
 * @export
 * @interface AgentTypesGet200Response
 */
export interface AgentTypesGet200Response {
    /**
     * 
     * @type {Array<AgentTypeRes>}
     * @memberof AgentTypesGet200Response
     */
    items?: Array<AgentTypeRes>;
    /**
     * 
     * @type {number}
     * @memberof AgentTypesGet200Response
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTypesGet200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTypesGet200Response
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof AgentTypesGet200Response
     */
    page?: number;
}

/**
 * Check if a given object implements the AgentTypesGet200Response interface.
 */
export function instanceOfAgentTypesGet200Response(value: object): value is AgentTypesGet200Response {
    return true;
}

export function AgentTypesGet200ResponseFromJSON(json: any): AgentTypesGet200Response {
    return AgentTypesGet200ResponseFromJSONTyped(json, false);
}

export function AgentTypesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AgentTypesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AgentTypeResFromJSON)),
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
    };
}

export function AgentTypesGet200ResponseToJSON(json: any): AgentTypesGet200Response {
    return AgentTypesGet200ResponseToJSONTyped(json, false);
}

export function AgentTypesGet200ResponseToJSONTyped(value?: AgentTypesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(AgentTypeResToJSON)),
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'page': value['page'],
    };
}

