/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Access role for the token
 * @export
 * @enum {string}
 */
export enum AuthRole {
    ADMIN = 'admin',
    PARTICIPANT = 'participant',
    AGENT = 'agent'
}


export function instanceOfAuthRole(value: any): boolean {
    for (const key in AuthRole) {
        if (Object.prototype.hasOwnProperty.call(AuthRole, key)) {
            if (AuthRole[key as keyof typeof AuthRole] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AuthRoleFromJSON(json: any): AuthRole {
    return AuthRoleFromJSONTyped(json, false);
}

export function AuthRoleFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRole {
    return json as AuthRole;
}

export function AuthRoleToJSON(value?: AuthRole | null): any {
    return value as any;
}

export function AuthRoleToJSONTyped(value: any, ignoreDiscriminator: boolean): AuthRole {
    return value as AuthRole;
}

