/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CompleteJobReq
 */
export interface CompleteJobReq {
    /**
     * 
     * @type {string}
     * @memberof CompleteJobReq
     */
    externalId?: string;
    /**
     * A generic properties.JSON object
     * @type {{ [key: string]: any; }}
     * @memberof CompleteJobReq
     */
    resources?: { [key: string]: any; };
}

/**
 * Check if a given object implements the CompleteJobReq interface.
 */
export function instanceOfCompleteJobReq(value: object): value is CompleteJobReq {
    return true;
}

export function CompleteJobReqFromJSON(json: any): CompleteJobReq {
    return CompleteJobReqFromJSONTyped(json, false);
}

export function CompleteJobReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompleteJobReq {
    if (json == null) {
        return json;
    }
    return {
        
        'externalId': json['externalId'] == null ? undefined : json['externalId'],
        'resources': json['resources'] == null ? undefined : json['resources'],
    };
}

export function CompleteJobReqToJSON(json: any): CompleteJobReq {
    return CompleteJobReqToJSONTyped(json, false);
}

export function CompleteJobReqToJSONTyped(value?: CompleteJobReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'externalId': value['externalId'],
        'resources': value['resources'],
    };
}

