/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetricEntryRes } from './MetricEntryRes';
import {
    MetricEntryResFromJSON,
    MetricEntryResFromJSONTyped,
    MetricEntryResToJSON,
    MetricEntryResToJSONTyped,
} from './MetricEntryRes';

/**
 * 
 * @export
 * @interface MetricEntriesGet200Response
 */
export interface MetricEntriesGet200Response {
    /**
     * 
     * @type {Array<MetricEntryRes>}
     * @memberof MetricEntriesGet200Response
     */
    items?: Array<MetricEntryRes>;
    /**
     * 
     * @type {number}
     * @memberof MetricEntriesGet200Response
     */
    totalItems?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricEntriesGet200Response
     */
    totalPages?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricEntriesGet200Response
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof MetricEntriesGet200Response
     */
    page?: number;
}

/**
 * Check if a given object implements the MetricEntriesGet200Response interface.
 */
export function instanceOfMetricEntriesGet200Response(value: object): value is MetricEntriesGet200Response {
    return true;
}

export function MetricEntriesGet200ResponseFromJSON(json: any): MetricEntriesGet200Response {
    return MetricEntriesGet200ResponseFromJSONTyped(json, false);
}

export function MetricEntriesGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricEntriesGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(MetricEntryResFromJSON)),
        'totalItems': json['totalItems'] == null ? undefined : json['totalItems'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
    };
}

export function MetricEntriesGet200ResponseToJSON(json: any): MetricEntriesGet200Response {
    return MetricEntriesGet200ResponseToJSONTyped(json, false);
}

export function MetricEntriesGet200ResponseToJSONTyped(value?: MetricEntriesGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(MetricEntryResToJSON)),
        'totalItems': value['totalItems'],
        'totalPages': value['totalPages'],
        'pageSize': value['pageSize'],
        'page': value['page'],
    };
}

