/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetricEntityType } from './MetricEntityType';
import {
    MetricEntityTypeFromJSON,
    MetricEntityTypeFromJSONTyped,
    MetricEntityTypeToJSON,
    MetricEntityTypeToJSONTyped,
} from './MetricEntityType';

/**
 * 
 * @export
 * @interface MetricTypeRes
 */
export interface MetricTypeRes {
    /**
     * 
     * @type {string}
     * @memberof MetricTypeRes
     */
    id?: string;
    /**
     * 
     * @type {MetricEntityType}
     * @memberof MetricTypeRes
     */
    entityType?: MetricEntityType;
    /**
     * 
     * @type {string}
     * @memberof MetricTypeRes
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof MetricTypeRes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof MetricTypeRes
     */
    updatedAt?: Date;
}



/**
 * Check if a given object implements the MetricTypeRes interface.
 */
export function instanceOfMetricTypeRes(value: object): value is MetricTypeRes {
    return true;
}

export function MetricTypeResFromJSON(json: any): MetricTypeRes {
    return MetricTypeResFromJSONTyped(json, false);
}

export function MetricTypeResFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricTypeRes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'entityType': json['entityType'] == null ? undefined : MetricEntityTypeFromJSON(json['entityType']),
        'name': json['name'] == null ? undefined : json['name'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function MetricTypeResToJSON(json: any): MetricTypeRes {
    return MetricTypeResToJSONTyped(json, false);
}

export function MetricTypeResToJSONTyped(value?: MetricTypeRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'entityType': MetricEntityTypeToJSON(value['entityType']),
        'name': value['name'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

