/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MetricEntityType {
    AGENT = 'Agent',
    SERVICE = 'Service',
    RESOURCE = 'Resource'
}


export function instanceOfMetricEntityType(value: any): boolean {
    for (const key in MetricEntityType) {
        if (Object.prototype.hasOwnProperty.call(MetricEntityType, key)) {
            if (MetricEntityType[key as keyof typeof MetricEntityType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MetricEntityTypeFromJSON(json: any): MetricEntityType {
    return MetricEntityTypeFromJSONTyped(json, false);
}

export function MetricEntityTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetricEntityType {
    return json as MetricEntityType;
}

export function MetricEntityTypeToJSON(value?: MetricEntityType | null): any {
    return value as any;
}

export function MetricEntityTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): MetricEntityType {
    return value as MetricEntityType;
}

