/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParticipantStatus } from './ParticipantStatus';
import {
    ParticipantStatusFromJSON,
    ParticipantStatusFromJSONTyped,
    ParticipantStatusToJSON,
    ParticipantStatusToJSONTyped,
} from './ParticipantStatus';

/**
 * 
 * @export
 * @interface ParticipantRes
 */
export interface ParticipantRes {
    /**
     * 
     * @type {string}
     * @memberof ParticipantRes
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ParticipantRes
     */
    name?: string;
    /**
     * 
     * @type {ParticipantStatus}
     * @memberof ParticipantRes
     */
    status?: ParticipantStatus;
    /**
     * 
     * @type {Date}
     * @memberof ParticipantRes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ParticipantRes
     */
    updatedAt?: Date;
}



/**
 * Check if a given object implements the ParticipantRes interface.
 */
export function instanceOfParticipantRes(value: object): value is ParticipantRes {
    return true;
}

export function ParticipantResFromJSON(json: any): ParticipantRes {
    return ParticipantResFromJSONTyped(json, false);
}

export function ParticipantResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ParticipantRes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'status': json['status'] == null ? undefined : ParticipantStatusFromJSON(json['status']),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ParticipantResToJSON(json: any): ParticipantRes {
    return ParticipantResToJSONTyped(json, false);
}

export function ParticipantResToJSONTyped(value?: ParticipantRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'status': ParticipantStatusToJSON(value['status']),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

