/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum ServiceStatus {
    CREATING = 'Creating',
    CREATED = 'Created',
    STARTING = 'Starting',
    STARTED = 'Started',
    STOPPING = 'Stopping',
    STOPPED = 'Stopped',
    HOT_UPDATING = 'HotUpdating',
    COLD_UPDATING = 'ColdUpdating',
    DELETING = 'Deleting',
    DELETED = 'Deleted'
}


export function instanceOfServiceStatus(value: any): boolean {
    for (const key in ServiceStatus) {
        if (Object.prototype.hasOwnProperty.call(ServiceStatus, key)) {
            if (ServiceStatus[key as keyof typeof ServiceStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ServiceStatusFromJSON(json: any): ServiceStatus {
    return ServiceStatusFromJSONTyped(json, false);
}

export function ServiceStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceStatus {
    return json as ServiceStatus;
}

export function ServiceStatusToJSON(value?: ServiceStatus | null): any {
    return value as any;
}

export function ServiceStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): ServiceStatus {
    return value as ServiceStatus;
}

