/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PropertyDefinition } from './PropertyDefinition';
import {
    PropertyDefinitionFromJSON,
    PropertyDefinitionFromJSONTyped,
    PropertyDefinitionToJSON,
    PropertyDefinitionToJSONTyped,
} from './PropertyDefinition';

/**
 * 
 * @export
 * @interface ServiceTypeRes
 */
export interface ServiceTypeRes {
    /**
     * 
     * @type {string}
     * @memberof ServiceTypeRes
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceTypeRes
     */
    name?: string;
    /**
     * properties.JSON schema defining validation rules for service properties
     * @type {{ [key: string]: PropertyDefinition; }}
     * @memberof ServiceTypeRes
     */
    propertySchema?: { [key: string]: PropertyDefinition; };
    /**
     * 
     * @type {Date}
     * @memberof ServiceTypeRes
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ServiceTypeRes
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the ServiceTypeRes interface.
 */
export function instanceOfServiceTypeRes(value: object): value is ServiceTypeRes {
    return true;
}

export function ServiceTypeResFromJSON(json: any): ServiceTypeRes {
    return ServiceTypeResFromJSONTyped(json, false);
}

export function ServiceTypeResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceTypeRes {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'propertySchema': json['propertySchema'] == null ? undefined : (mapValues(json['propertySchema'], PropertyDefinitionFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
    };
}

export function ServiceTypeResToJSON(json: any): ServiceTypeRes {
    return ServiceTypeResToJSONTyped(json, false);
}

export function ServiceTypeResToJSONTyped(value?: ServiceTypeRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'propertySchema': value['propertySchema'] == null ? undefined : (mapValues(value['propertySchema'], PropertyDefinitionToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
    };
}

