/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ValidationError } from './ValidationError';
import {
    ValidationErrorFromJSON,
    ValidationErrorFromJSONTyped,
    ValidationErrorToJSON,
    ValidationErrorToJSONTyped,
} from './ValidationError';

/**
 * 
 * @export
 * @interface ValidatePropertiesRes
 */
export interface ValidatePropertiesRes {
    /**
     * Whether the properties are valid
     * @type {boolean}
     * @memberof ValidatePropertiesRes
     */
    valid?: boolean;
    /**
     * Array of validation errors (empty if valid)
     * @type {Array<ValidationError>}
     * @memberof ValidatePropertiesRes
     */
    errors?: Array<ValidationError>;
}

/**
 * Check if a given object implements the ValidatePropertiesRes interface.
 */
export function instanceOfValidatePropertiesRes(value: object): value is ValidatePropertiesRes {
    return true;
}

export function ValidatePropertiesResFromJSON(json: any): ValidatePropertiesRes {
    return ValidatePropertiesResFromJSONTyped(json, false);
}

export function ValidatePropertiesResFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatePropertiesRes {
    if (json == null) {
        return json;
    }
    return {
        
        'valid': json['valid'] == null ? undefined : json['valid'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(ValidationErrorFromJSON)),
    };
}

export function ValidatePropertiesResToJSON(json: any): ValidatePropertiesRes {
    return ValidatePropertiesResToJSONTyped(json, false);
}

export function ValidatePropertiesResToJSONTyped(value?: ValidatePropertiesRes | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'valid': value['valid'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(ValidationErrorToJSON)),
    };
}

