/* tslint:disable */
/* eslint-disable */
/**
 * Fulcrum Core API
 * A comprehensive cloud infrastructure management system designed to orchestrate and monitor distributed cloud resources across multiple providers.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ValidatePropertiesReq
 */
export interface ValidatePropertiesReq {
    /**
     * Properties to validate against the schema
     * @type {{ [key: string]: any; }}
     * @memberof ValidatePropertiesReq
     */
    properties: { [key: string]: any; };
}

/**
 * Check if a given object implements the ValidatePropertiesReq interface.
 */
export function instanceOfValidatePropertiesReq(value: object): value is ValidatePropertiesReq {
    if (!('properties' in value) || value['properties'] === undefined) return false;
    return true;
}

export function ValidatePropertiesReqFromJSON(json: any): ValidatePropertiesReq {
    return ValidatePropertiesReqFromJSONTyped(json, false);
}

export function ValidatePropertiesReqFromJSONTyped(json: any, ignoreDiscriminator: boolean): ValidatePropertiesReq {
    if (json == null) {
        return json;
    }
    return {
        
        'properties': json['properties'],
    };
}

export function ValidatePropertiesReqToJSON(json: any): ValidatePropertiesReq {
    return ValidatePropertiesReqToJSONTyped(json, false);
}

export function ValidatePropertiesReqToJSONTyped(value?: ValidatePropertiesReq | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'properties': value['properties'],
    };
}

