all: false
dir: "{{.InterfaceDir}}/mocks"
filename: "{{.InterfaceName | snakecase}}.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "Mock{{.InterfaceName}}"
pkgname: "mocks"
inpackage: false
recursive: false
template: testify

packages:
  github.com/fulcrumproject/core/pkg/domain:
    config:
      all: true

  github.com/fulcrumproject/core/pkg/auth:
    config:
      all: true
