all: false
dir: "{{.InterfaceDir}}"
filename: "mocks.go"
force-file-write: true
formatter: goimports
log-level: info
structname: "Mock{{.InterfaceName}}"
inpackage: true
recursive: false
template: testify

packages:
  github.com/fulcrumproject/core/pkg/domain:
    config:
      all: true

  github.com/fulcrumproject/core/pkg/auth:
    config:
      all: true

  github.com/fulcrumproject/core/pkg/schema:
    config:
      all: true
