services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - FULCRUM_DB_HOST=postgres
      - FULCRUM_DB_USER=fulcrum
      - FULCRUM_DB_PASSWORD=fulcrum_password
      - FULCRUM_DB_NAME=fulcrum_db
      - FULCRUM_DB_PORT=5432
      - FULCRUM_DB_SSL_MODE=disable
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - fulcrum-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fulcrum
      - POSTGRES_PASSWORD=fulcrum_password
      - POSTGRES_DB=fulcrum_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fulcrum -d fulcrum_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - fulcrum-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    command: ["start-dev", "--http-port", "8080", "--https-port", "8443"]
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - fulcrum-network

  keycloak-provisioning:
    image: quay.io/adorsys/keycloak-config-cli:latest
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: "true"
      KEYCLOAK_AVAILABILITYCHECK_TIMEOUT: "120s"
      IMPORT_FILES_LOCATION: "/config/*"
    volumes:
      - ./test/keycloak:/config:z
    networks:
      - fulcrum-network

volumes:
  postgres_data:

networks:
  fulcrum-network:
    driver: bridge
