# Broker API Tests

@baseUrl = http://localhost:3000/api/v1
@adminToken = admin-test-token

### List all brokers
GET {{baseUrl}}/brokers
Authorization: Bearer {{adminToken}}

### Create a new broker
# @name createBroker
POST {{baseUrl}}/brokers
Authorization: Bearer {{adminToken}}

{
  "name": "Test Broker"
}

@brokerId = {{createBroker.response.body.$.id}}

### Create a new broker 2
# @name createBroker2
POST {{baseUrl}}/brokers
Authorization: Bearer {{adminToken}}

{
  "name": "Test Broker 2"
}

@brokerId2 = {{createBroker2.response.body.$.id}}

### Get broker by ID
GET {{baseUrl}}/brokers/{{brokerId}}
Authorization: Bearer {{adminToken}}

### Update broker
PATCH {{baseUrl}}/brokers/{{brokerId}}
Authorization: Bearer {{adminToken}}

{
  "name": "Updated Broker Name"
}

### Create a new broker token
# @name createBrokerToken
POST {{baseUrl}}/tokens
Authorization: Bearer {{adminToken}}

{
  "name": "Test Broker Token",
  "role": "broker",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{brokerId}}"
}

@brokerToken = {{createBrokerToken.response.body.$.value}}

### Get broker by ID
GET {{baseUrl}}/brokers/{{brokerId}}
Authorization: Bearer {{brokerToken}}

### Get brokers
GET {{baseUrl}}/brokers
Authorization: Bearer {{brokerToken}}

### Get brokers SHOULD FAIL 403
GET {{baseUrl}}/brokers/{{brokerId2}}
Authorization: Bearer {{brokerToken}}

### Delete broker
DELETE {{baseUrl}}/brokers/{{brokerId}}
Authorization: Bearer {{adminToken}}