### Test Service API

### Variables
@baseUrl = http://localhost:3000/api/v1
@adminToken = admin-test-token

### Create a provider for testing
# @name createProvider
POST {{baseUrl}}/providers
Authorization: Bearer {{adminToken}}

{
    "name": "CloudConf Service Provider",
    "state": "Enabled",
    "countryCode": "IT",
    "attributes": {
        "certifications": ["ISO-9001","ISO-27001"]
    }
}

@providerId = {{createProvider.response.body.$.id}}

### Create an agent
# @name createAgent
POST {{baseUrl}}/agents
Authorization: Bearer {{adminToken}}

{
    "name": "VM Agent",
    "countryCode": "IT",
    "agentTypeId": "0195c3c6-4c7d-7e3c-b481-f276e17a7bec",
    "providerId": "{{providerId}}",
    "attributes": {
        "certifications": ["ISO-27001"],
        "region": ["IT"]
    }
}

@agentId = {{createAgent.response.body.$.id}}

### Create a new agent token
# @name createAgentToken
POST {{baseUrl}}/tokens
Authorization: Bearer {{adminToken}}

{
  "name": "Test Agent Token",
  "role": "agent",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{agentId}}"
}

@agentToken = {{createAgentToken.response.body.$.value}}

### Get agent's own information via authenticated endpoint
# @name getAgentMe
GET {{baseUrl}}/agents/me
Authorization: Bearer {{agentToken}}

### Create a new consumer
# @name createConsumer
POST {{baseUrl}}/consumers
Authorization: Bearer {{adminToken}}

{
  "name": "System Integrator"
}

@consumerId = {{createConsumer.response.body.$.id}}

### Create a new consumer token
# @name createConsumerToken
POST {{baseUrl}}/tokens
Authorization: Bearer {{adminToken}}

{
  "name": "System Integrator Token",
  "role": "consumer",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{consumerId}}"
}

@consumerToken = {{createConsumerToken.response.body.$.value}}

### Create a service group
# @name createServiceGroup
POST {{baseUrl}}/service-groups
Authorization: Bearer {{consumerToken}}

{
    "name": "Project CloudConf2025",
    "consumerId": "{{consumerId}}"
}

@serviceGroupId = {{createServiceGroup.response.body.$.id}}

### Create a new service
# @name createService
POST {{baseUrl}}/services
Authorization: Bearer {{consumerToken}}

{
    "name": "Proxmox VM",
    "attributes": {
        "region": ["IT"],
        "tier": ["3"],
        "certifications": ["ISO-27001"]
    },
    "properties": {
        "cpu": 4,
        "memory": 8
    },
    "agentId": "{{agentId}}",
    "serviceTypeId": "0195c3c8-69e5-7806-9598-8523c01ea54f",
    "groupId": "{{serviceGroupId}}"
}

@serviceId = {{createService.response.body.$.id}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Update name - Should not trigger a job
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

{
    "name": "Proxmox VM - CloudConf2025"
}

### Start Service
POST {{baseUrl}}/services/{{serviceId}}/start
Authorization: Bearer {{consumerToken}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Hot update vm state
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

{
    "properties": {
        "cpu": 8,
        "memory": 24
    }
}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Stop Service
POST {{baseUrl}}/services/{{serviceId}}/stop
Authorization: Bearer {{consumerToken}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Cold update vm state
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

{
    "properties": {
        "cpu": 4,
        "memory": 16
    }
}

### Retry Service Operation
POST {{baseUrl}}/services/{{serviceId}}/retry
Authorization: Bearer {{consumerToken}}

### Delete a service
DELETE {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{consumerToken}}

### List all services
GET {{baseUrl}}/services
Authorization: Bearer {{consumerToken}}


