# Consumer API Tests

@baseUrl = http://localhost:3000/api/v1
@adminToken = change-me

### List all consumers
GET {{baseUrl}}/participants
Authorization: Bearer {{adminToken}}

### Create a new consumer
# @name createConsumer
POST {{baseUrl}}/participants
Authorization: Bearer {{adminToken}}

{
  "name": "Test Consumer",
  "status": "Enabled"
}

@consumerId = {{createConsumer.response.body.$.id}}

### Create a new consumer 2
# @name createConsumer2
POST {{baseUrl}}/participants
Authorization: Bearer {{adminToken}}

{
  "name": "Test Consumer 2",
  "status": "Disabled"
}

@consumerId2 = {{createConsumer2.response.body.$.id}}

### Get consumer by ID
GET {{baseUrl}}/participants/{{consumerId}}
Authorization: Bearer {{adminToken}}

### Update consumer
PATCH {{baseUrl}}/participants/{{consumerId}}
Authorization: Bearer {{adminToken}}

{
  "name": "Updated Consumer Name"
}

### Create a new consumer token
# @name createConsumerToken
POST {{baseUrl}}/tokens
Authorization: Bearer {{adminToken}}

{
  "name": "Test Consumer Token",
  "role": "participant",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{consumerId}}"
}

@consumerToken = {{createConsumerToken.response.body.$.value}}

### Get consumer by ID
GET {{baseUrl}}/participants/{{consumerId}}
Authorization: Bearer {{consumerToken}}

### Get consumers
GET {{baseUrl}}/participants
Authorization: Bearer {{consumerToken}}

### Get consumers SHOULD FAIL 403
GET {{baseUrl}}/participants/{{consumerId2}}
Authorization: Bearer {{consumerToken}}

### Delete consumer
DELETE {{baseUrl}}/participants/{{consumerId}}
Authorization: Bearer {{adminToken}}