### Service Pool Operations
### This file tests operations for service pools

### Variables
@baseUrl = http://localhost:3000/api/v1
@adminToken = change-me

### Get all service pools
GET {{baseUrl}}/service-pools
Authorization: Bearer {{adminToken}}

### Get all service pools with filter by generatorType
GET {{baseUrl}}/service-pools?generatorType=list
Authorization: Bearer {{adminToken}}

### Create Provider (moved here to use in service options and pools)
# @name createProvider
POST {{baseUrl}}/participants
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Test Provider {{$guid}}",
    "status": "Enabled",
    "attributes": {
        "type": ["test"]
    }
}

### Create Service Pool Set
# @name createPoolSet
POST {{baseUrl}}/service-pool-sets
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Test Pools {{$guid}}",
    "providerId": "{{createProvider.response.body.id}}"
}

### Create an service pool
# @name createServicePool
POST {{baseUrl}}/service-pools
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
    "name": "Public IP Pool",
    "type": "public_ip",
    "propertyType": "string",
    "generatorType": "list",
    "servicePoolSetId": "{{createPoolSet.response.body.id}}"
}

@servicePoolId = {{createServicePool.response.body.$.id}}

### Create an service pool value
# @name createServicePoolValue
POST {{baseUrl}}/service-pool-values
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "name": "192.168.1.10",
  "value": "192.168.1.10",
  "servicePoolId": "{{servicePoolId}}"
}

@servicePoolValueId = {{createServicePoolValue.response.body.$.id}}

### Get a specific service pool
GET {{baseUrl}}/service-pools/{{servicePoolId}}
Authorization: Bearer {{adminToken}}

### Update an service pool
PATCH {{baseUrl}}/service-pools/{{servicePoolId}}
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "name": "Updated Pool Name"
}

### Delete an service pool (should fail if has associated value)
DELETE {{baseUrl}}/service-pools/{{servicePoolId}}
Authorization: Bearer {{adminToken}}

### Delete an service pool value
DELETE {{baseUrl}}/service-pool-values/{{servicePoolValueId}}
Authorization: Bearer {{adminToken}}
