### Test ServiceGroup API

### Variables
@baseUrl = http://localhost:3000/api/v1
@adminToken = admin-test-token

### Create a new consumer
# @name createConsumer
POST {{baseUrl}}/participants
Authorization: Bearer {{adminToken}}

{
  "name": "Test Consumer For Service Group",
  "state": "Disabled"
}

@consumerId = {{createConsumer.response.body.$.id}}

### Create a new service group
# @name createServiceGroup
POST {{baseUrl}}/service-groups
Authorization: Bearer {{adminToken}}

{
    "name": "Database",
    "consumerId": "{{consumerId}}"
}

@serviceGroupId = {{createServiceGroup.response.body.$.id}}

### Get a service group by ID
GET {{baseUrl}}/service-groups/{{serviceGroupId}}
Authorization: Bearer {{adminToken}}

### List all service groups
GET {{baseUrl}}/service-groups?name=Database
Authorization: Bearer {{adminToken}}

### Update a service group
PATCH {{baseUrl}}/service-groups/{{serviceGroupId}}
Authorization: Bearer {{adminToken}}

{
    "name": "Database Services Updated"
}

### Delete a service group
DELETE {{baseUrl}}/service-groups/{{serviceGroupId}}
Authorization: Bearer {{adminToken}}
