### Test Service API

### Variables
@baseUrl = http://localhost:3000/api/v1
@adminToken = admin-test-token

### Create a provider for testing
# @name createProvider
POST {{baseUrl}}/providers
Authorization: Bearer {{adminToken}}

{
    "name": "Test Service Provider",
    "state": "Enabled",
    "countryCode": "US",
    "attributes": {
        "type": ["test"]
    }
}

@providerId = {{createProvider.response.body.$.id}}

### Create an agent
# @name createAgent
POST {{baseUrl}}/agents
Authorization: Bearer {{adminToken}}

{
    "name": "Test Agent",
    "countryCode": "US",
    "agentTypeId": "0195c3c6-4c7d-7e3c-b481-f276e17a7bec",
    "providerId": "{{providerId}}"
}

@agentId = {{createAgent.response.body.$.id}}

### Create a new agent token
# @name createAgentToken
POST {{baseUrl}}/tokens?{{agentId}}
Authorization: Bearer {{adminToken}}

{
  "name": "Test Agent Token",
  "role": "agent",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{agentId}}"
}

@agentToken = {{createAgentToken.response.body.$.value}}

### Get agent's own information via authenticated endpoint
# @name getAgentMe
GET {{baseUrl}}/agents/me
Authorization: Bearer {{agentToken}}

### Create a new broker
# @name createBroker
POST {{baseUrl}}/brokers
Authorization: Bearer {{adminToken}}

{
  "name": "Test Broker"
}

@brokerId = {{createBroker.response.body.$.id}}

### Create a new broker token
# @name createBrokerToken
POST {{baseUrl}}/tokens
Authorization: Bearer {{adminToken}}

{
  "name": "Test Broker Token",
  "role": "broker",
  "expireAt": "{{$datetime iso8601 1 y}}",
  "scopeId": "{{brokerId}}"
}

@brokerToken = {{createBrokerToken.response.body.$.value}}

### Create a service group
# @name createServiceGroup
POST {{baseUrl}}/service-groups
Authorization: Bearer {{brokerToken}}

{
    "name": "Test Service Group",
    "brokerId": "{{brokerId}}"
}

@serviceGroupId = {{createServiceGroup.response.body.$.id}}

### Create a new service
# @name createService
POST {{baseUrl}}/services
Authorization: Bearer {{brokerToken}}

{
    "name": "Test Service",
    "attributes": {
        "tier": ["4"]
    },
    "properties": {
        "cpu": 4,
        "memory": 8
    },
    "agentId": "{{agentId}}",
    "serviceTypeId": "0195c3c8-69e5-7806-9598-8523c01ea54f",
    "groupId": "{{serviceGroupId}}"
}

@serviceId = {{createService.response.body.$.id}}

### Get a service by ID
GET {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{brokerToken}}

### Update name - Should not trigger a job
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{brokerToken}}

{
    "name": "Updated Service"
}

### Start Service
POST {{baseUrl}}/services/{{serviceId}}/start
Authorization: Bearer {{brokerToken}}


### Hot update vm state
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{brokerToken}}

{
    "properties": {
        "cpu": 4,
        "memory": 12
    }
}

### Stop Service
POST {{baseUrl}}/services/{{serviceId}}/stop
Authorization: Bearer {{brokerToken}}

### Cold update vm state
PATCH {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{brokerToken}}

{
    "properties": {
        "cpu": 4,
        "memory": 16
    }
}

### Retry Service Operation
POST {{baseUrl}}/services/{{serviceId}}/retry
Authorization: Bearer {{brokerToken}}

### Delete a service NOT WORKING SEE TODO
DELETE {{baseUrl}}/services/{{serviceId}}
Authorization: Bearer {{brokerToken}}

### List all services
GET {{baseUrl}}/services
Authorization: Bearer {{brokerToken}}

### List services with filters
GET {{baseUrl}}/services?name=Updated Service
Authorization: Bearer {{brokerToken}}

### List services with pagination
GET {{baseUrl}}/services?page=1&pageSize=10
Authorization: Bearer {{brokerToken}}

