// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBaseEntityQuerier creates a new instance of MockBaseEntityQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseEntityQuerier[T domain.Entity](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseEntityQuerier[T] {
	mock := &MockBaseEntityQuerier[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBaseEntityQuerier is an autogenerated mock type for the BaseEntityQuerier type
type MockBaseEntityQuerier[T domain.Entity] struct {
	mock.Mock
}

type MockBaseEntityQuerier_Expecter[T domain.Entity] struct {
	mock *mock.Mock
}

func (_m *MockBaseEntityQuerier[T]) EXPECT() *MockBaseEntityQuerier_Expecter[T] {
	return &MockBaseEntityQuerier_Expecter[T]{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockBaseEntityQuerier
func (_mock *MockBaseEntityQuerier[T]) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityQuerier_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockBaseEntityQuerier_AuthScope_Call[T domain.Entity] struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockBaseEntityQuerier_Expecter[T]) AuthScope(ctx interface{}, id interface{}) *MockBaseEntityQuerier_AuthScope_Call[T] {
	return &MockBaseEntityQuerier_AuthScope_Call[T]{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockBaseEntityQuerier_AuthScope_Call[T]) Run(run func(ctx context.Context, id properties.UUID)) *MockBaseEntityQuerier_AuthScope_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityQuerier_AuthScope_Call[T]) Return(objectScope auth.ObjectScope, err error) *MockBaseEntityQuerier_AuthScope_Call[T] {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockBaseEntityQuerier_AuthScope_Call[T]) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockBaseEntityQuerier_AuthScope_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockBaseEntityQuerier
func (_mock *MockBaseEntityQuerier[T]) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityQuerier_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockBaseEntityQuerier_Count_Call[T domain.Entity] struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBaseEntityQuerier_Expecter[T]) Count(ctx interface{}) *MockBaseEntityQuerier_Count_Call[T] {
	return &MockBaseEntityQuerier_Count_Call[T]{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockBaseEntityQuerier_Count_Call[T]) Run(run func(ctx context.Context)) *MockBaseEntityQuerier_Count_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseEntityQuerier_Count_Call[T]) Return(n int64, err error) *MockBaseEntityQuerier_Count_Call[T] {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBaseEntityQuerier_Count_Call[T]) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockBaseEntityQuerier_Count_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockBaseEntityQuerier
func (_mock *MockBaseEntityQuerier[T]) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityQuerier_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockBaseEntityQuerier_Exists_Call[T domain.Entity] struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockBaseEntityQuerier_Expecter[T]) Exists(ctx interface{}, id interface{}) *MockBaseEntityQuerier_Exists_Call[T] {
	return &MockBaseEntityQuerier_Exists_Call[T]{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockBaseEntityQuerier_Exists_Call[T]) Run(run func(ctx context.Context, id properties.UUID)) *MockBaseEntityQuerier_Exists_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityQuerier_Exists_Call[T]) Return(b bool, err error) *MockBaseEntityQuerier_Exists_Call[T] {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBaseEntityQuerier_Exists_Call[T]) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockBaseEntityQuerier_Exists_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBaseEntityQuerier
func (_mock *MockBaseEntityQuerier[T]) Get(ctx context.Context, id properties.UUID) (*T, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*T, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *T); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityQuerier_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBaseEntityQuerier_Get_Call[T domain.Entity] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockBaseEntityQuerier_Expecter[T]) Get(ctx interface{}, id interface{}) *MockBaseEntityQuerier_Get_Call[T] {
	return &MockBaseEntityQuerier_Get_Call[T]{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockBaseEntityQuerier_Get_Call[T]) Run(run func(ctx context.Context, id properties.UUID)) *MockBaseEntityQuerier_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityQuerier_Get_Call[T]) Return(v *T, err error) *MockBaseEntityQuerier_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBaseEntityQuerier_Get_Call[T]) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*T, error)) *MockBaseEntityQuerier_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBaseEntityQuerier
func (_mock *MockBaseEntityQuerier[T]) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[T], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[T]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[T], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[T]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[T])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityQuerier_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBaseEntityQuerier_List_Call[T domain.Entity] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockBaseEntityQuerier_Expecter[T]) List(ctx interface{}, scope interface{}, req interface{}) *MockBaseEntityQuerier_List_Call[T] {
	return &MockBaseEntityQuerier_List_Call[T]{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockBaseEntityQuerier_List_Call[T]) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockBaseEntityQuerier_List_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBaseEntityQuerier_List_Call[T]) Return(pageRes *domain.PageRes[T], err error) *MockBaseEntityQuerier_List_Call[T] {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockBaseEntityQuerier_List_Call[T]) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[T], error)) *MockBaseEntityQuerier_List_Call[T] {
	_c.Call.Return(run)
	return _c
}
