// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBaseEntityRepository creates a new instance of MockBaseEntityRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseEntityRepository[T domain.Entity](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseEntityRepository[T] {
	mock := &MockBaseEntityRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBaseEntityRepository is an autogenerated mock type for the BaseEntityRepository type
type MockBaseEntityRepository[T domain.Entity] struct {
	mock.Mock
}

type MockBaseEntityRepository_Expecter[T domain.Entity] struct {
	mock *mock.Mock
}

func (_m *MockBaseEntityRepository[T]) EXPECT() *MockBaseEntityRepository_Expecter[T] {
	return &MockBaseEntityRepository_Expecter[T]{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityRepository_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockBaseEntityRepository_AuthScope_Call[T domain.Entity] struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockBaseEntityRepository_Expecter[T]) AuthScope(ctx interface{}, id interface{}) *MockBaseEntityRepository_AuthScope_Call[T] {
	return &MockBaseEntityRepository_AuthScope_Call[T]{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockBaseEntityRepository_AuthScope_Call[T]) Run(run func(ctx context.Context, id properties.UUID)) *MockBaseEntityRepository_AuthScope_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_AuthScope_Call[T]) Return(objectScope auth.ObjectScope, err error) *MockBaseEntityRepository_AuthScope_Call[T] {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockBaseEntityRepository_AuthScope_Call[T]) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockBaseEntityRepository_AuthScope_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockBaseEntityRepository_Count_Call[T domain.Entity] struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockBaseEntityRepository_Expecter[T]) Count(ctx interface{}) *MockBaseEntityRepository_Count_Call[T] {
	return &MockBaseEntityRepository_Count_Call[T]{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockBaseEntityRepository_Count_Call[T]) Run(run func(ctx context.Context)) *MockBaseEntityRepository_Count_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_Count_Call[T]) Return(n int64, err error) *MockBaseEntityRepository_Count_Call[T] {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockBaseEntityRepository_Count_Call[T]) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockBaseEntityRepository_Count_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) Create(ctx context.Context, entity *T) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBaseEntityRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockBaseEntityRepository_Create_Call[T domain.Entity] struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *T
func (_e *MockBaseEntityRepository_Expecter[T]) Create(ctx interface{}, entity interface{}) *MockBaseEntityRepository_Create_Call[T] {
	return &MockBaseEntityRepository_Create_Call[T]{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockBaseEntityRepository_Create_Call[T]) Run(run func(ctx context.Context, entity *T)) *MockBaseEntityRepository_Create_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *T
		if args[1] != nil {
			arg1 = args[1].(*T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_Create_Call[T]) Return(err error) *MockBaseEntityRepository_Create_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBaseEntityRepository_Create_Call[T]) RunAndReturn(run func(ctx context.Context, entity *T) error) *MockBaseEntityRepository_Create_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) Delete(ctx context.Context, id properties.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBaseEntityRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBaseEntityRepository_Delete_Call[T domain.Entity] struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockBaseEntityRepository_Expecter[T]) Delete(ctx interface{}, id interface{}) *MockBaseEntityRepository_Delete_Call[T] {
	return &MockBaseEntityRepository_Delete_Call[T]{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockBaseEntityRepository_Delete_Call[T]) Run(run func(ctx context.Context, id properties.UUID)) *MockBaseEntityRepository_Delete_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_Delete_Call[T]) Return(err error) *MockBaseEntityRepository_Delete_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBaseEntityRepository_Delete_Call[T]) RunAndReturn(run func(ctx context.Context, id properties.UUID) error) *MockBaseEntityRepository_Delete_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockBaseEntityRepository_Exists_Call[T domain.Entity] struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockBaseEntityRepository_Expecter[T]) Exists(ctx interface{}, id interface{}) *MockBaseEntityRepository_Exists_Call[T] {
	return &MockBaseEntityRepository_Exists_Call[T]{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockBaseEntityRepository_Exists_Call[T]) Run(run func(ctx context.Context, id properties.UUID)) *MockBaseEntityRepository_Exists_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_Exists_Call[T]) Return(b bool, err error) *MockBaseEntityRepository_Exists_Call[T] {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBaseEntityRepository_Exists_Call[T]) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockBaseEntityRepository_Exists_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) Get(ctx context.Context, id properties.UUID) (*T, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *T
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*T, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *T); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*T)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBaseEntityRepository_Get_Call[T domain.Entity] struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockBaseEntityRepository_Expecter[T]) Get(ctx interface{}, id interface{}) *MockBaseEntityRepository_Get_Call[T] {
	return &MockBaseEntityRepository_Get_Call[T]{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockBaseEntityRepository_Get_Call[T]) Run(run func(ctx context.Context, id properties.UUID)) *MockBaseEntityRepository_Get_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_Get_Call[T]) Return(v *T, err error) *MockBaseEntityRepository_Get_Call[T] {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockBaseEntityRepository_Get_Call[T]) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*T, error)) *MockBaseEntityRepository_Get_Call[T] {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[T], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[T]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[T], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[T]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[T])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBaseEntityRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockBaseEntityRepository_List_Call[T domain.Entity] struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockBaseEntityRepository_Expecter[T]) List(ctx interface{}, scope interface{}, req interface{}) *MockBaseEntityRepository_List_Call[T] {
	return &MockBaseEntityRepository_List_Call[T]{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockBaseEntityRepository_List_Call[T]) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockBaseEntityRepository_List_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_List_Call[T]) Return(pageRes *domain.PageRes[T], err error) *MockBaseEntityRepository_List_Call[T] {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockBaseEntityRepository_List_Call[T]) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[T], error)) *MockBaseEntityRepository_List_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockBaseEntityRepository
func (_mock *MockBaseEntityRepository[T]) Save(ctx context.Context, entity *T) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *T) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBaseEntityRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockBaseEntityRepository_Save_Call[T domain.Entity] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *T
func (_e *MockBaseEntityRepository_Expecter[T]) Save(ctx interface{}, entity interface{}) *MockBaseEntityRepository_Save_Call[T] {
	return &MockBaseEntityRepository_Save_Call[T]{Call: _e.mock.On("Save", ctx, entity)}
}

func (_c *MockBaseEntityRepository_Save_Call[T]) Run(run func(ctx context.Context, entity *T)) *MockBaseEntityRepository_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *T
		if args[1] != nil {
			arg1 = args[1].(*T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBaseEntityRepository_Save_Call[T]) Return(err error) *MockBaseEntityRepository_Save_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBaseEntityRepository_Save_Call[T]) RunAndReturn(run func(ctx context.Context, entity *T) error) *MockBaseEntityRepository_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}
