// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventSubscriptionRepository creates a new instance of MockEventSubscriptionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSubscriptionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSubscriptionRepository {
	mock := &MockEventSubscriptionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventSubscriptionRepository is an autogenerated mock type for the EventSubscriptionRepository type
type MockEventSubscriptionRepository struct {
	mock.Mock
}

type MockEventSubscriptionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventSubscriptionRepository) EXPECT() *MockEventSubscriptionRepository_Expecter {
	return &MockEventSubscriptionRepository_Expecter{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockEventSubscriptionRepository_AuthScope_Call struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventSubscriptionRepository_Expecter) AuthScope(ctx interface{}, id interface{}) *MockEventSubscriptionRepository_AuthScope_Call {
	return &MockEventSubscriptionRepository_AuthScope_Call{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockEventSubscriptionRepository_AuthScope_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventSubscriptionRepository_AuthScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_AuthScope_Call) Return(objectScope auth.ObjectScope, err error) *MockEventSubscriptionRepository_AuthScope_Call {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_AuthScope_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockEventSubscriptionRepository_AuthScope_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockEventSubscriptionRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventSubscriptionRepository_Expecter) Count(ctx interface{}) *MockEventSubscriptionRepository_Count_Call {
	return &MockEventSubscriptionRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockEventSubscriptionRepository_Count_Call) Run(run func(ctx context.Context)) *MockEventSubscriptionRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_Count_Call) Return(n int64, err error) *MockEventSubscriptionRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockEventSubscriptionRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) Create(ctx context.Context, entity *domain.EventSubscription) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.EventSubscription) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSubscriptionRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventSubscriptionRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.EventSubscription
func (_e *MockEventSubscriptionRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockEventSubscriptionRepository_Create_Call {
	return &MockEventSubscriptionRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockEventSubscriptionRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.EventSubscription)) *MockEventSubscriptionRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.EventSubscription
		if args[1] != nil {
			arg1 = args[1].(*domain.EventSubscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_Create_Call) Return(err error) *MockEventSubscriptionRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSubscriptionRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.EventSubscription) error) *MockEventSubscriptionRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) Delete(ctx context.Context, id properties.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSubscriptionRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEventSubscriptionRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventSubscriptionRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockEventSubscriptionRepository_Delete_Call {
	return &MockEventSubscriptionRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEventSubscriptionRepository_Delete_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventSubscriptionRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_Delete_Call) Return(err error) *MockEventSubscriptionRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSubscriptionRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) error) *MockEventSubscriptionRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBySubscriberID provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) DeleteBySubscriberID(ctx context.Context, subscriberID string) error {
	ret := _mock.Called(ctx, subscriberID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBySubscriberID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, subscriberID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSubscriptionRepository_DeleteBySubscriberID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBySubscriberID'
type MockEventSubscriptionRepository_DeleteBySubscriberID_Call struct {
	*mock.Call
}

// DeleteBySubscriberID is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriberID string
func (_e *MockEventSubscriptionRepository_Expecter) DeleteBySubscriberID(ctx interface{}, subscriberID interface{}) *MockEventSubscriptionRepository_DeleteBySubscriberID_Call {
	return &MockEventSubscriptionRepository_DeleteBySubscriberID_Call{Call: _e.mock.On("DeleteBySubscriberID", ctx, subscriberID)}
}

func (_c *MockEventSubscriptionRepository_DeleteBySubscriberID_Call) Run(run func(ctx context.Context, subscriberID string)) *MockEventSubscriptionRepository_DeleteBySubscriberID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_DeleteBySubscriberID_Call) Return(err error) *MockEventSubscriptionRepository_DeleteBySubscriberID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSubscriptionRepository_DeleteBySubscriberID_Call) RunAndReturn(run func(ctx context.Context, subscriberID string) error) *MockEventSubscriptionRepository_DeleteBySubscriberID_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockEventSubscriptionRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventSubscriptionRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockEventSubscriptionRepository_Exists_Call {
	return &MockEventSubscriptionRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockEventSubscriptionRepository_Exists_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventSubscriptionRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_Exists_Call) Return(b bool, err error) *MockEventSubscriptionRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockEventSubscriptionRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// ExistsBySubscriberID provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) ExistsBySubscriberID(ctx context.Context, subscriberID string) (bool, error) {
	ret := _mock.Called(ctx, subscriberID)

	if len(ret) == 0 {
		panic("no return value specified for ExistsBySubscriberID")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, subscriberID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, subscriberID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subscriberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_ExistsBySubscriberID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsBySubscriberID'
type MockEventSubscriptionRepository_ExistsBySubscriberID_Call struct {
	*mock.Call
}

// ExistsBySubscriberID is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriberID string
func (_e *MockEventSubscriptionRepository_Expecter) ExistsBySubscriberID(ctx interface{}, subscriberID interface{}) *MockEventSubscriptionRepository_ExistsBySubscriberID_Call {
	return &MockEventSubscriptionRepository_ExistsBySubscriberID_Call{Call: _e.mock.On("ExistsBySubscriberID", ctx, subscriberID)}
}

func (_c *MockEventSubscriptionRepository_ExistsBySubscriberID_Call) Run(run func(ctx context.Context, subscriberID string)) *MockEventSubscriptionRepository_ExistsBySubscriberID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_ExistsBySubscriberID_Call) Return(b bool, err error) *MockEventSubscriptionRepository_ExistsBySubscriberID_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_ExistsBySubscriberID_Call) RunAndReturn(run func(ctx context.Context, subscriberID string) (bool, error)) *MockEventSubscriptionRepository_ExistsBySubscriberID_Call {
	_c.Call.Return(run)
	return _c
}

// FindBySubscriberID provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) FindBySubscriberID(ctx context.Context, subscriberID string) (*domain.EventSubscription, error) {
	ret := _mock.Called(ctx, subscriberID)

	if len(ret) == 0 {
		panic("no return value specified for FindBySubscriberID")
	}

	var r0 *domain.EventSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.EventSubscription, error)); ok {
		return returnFunc(ctx, subscriberID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.EventSubscription); ok {
		r0 = returnFunc(ctx, subscriberID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, subscriberID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_FindBySubscriberID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindBySubscriberID'
type MockEventSubscriptionRepository_FindBySubscriberID_Call struct {
	*mock.Call
}

// FindBySubscriberID is a helper method to define mock.On call
//   - ctx context.Context
//   - subscriberID string
func (_e *MockEventSubscriptionRepository_Expecter) FindBySubscriberID(ctx interface{}, subscriberID interface{}) *MockEventSubscriptionRepository_FindBySubscriberID_Call {
	return &MockEventSubscriptionRepository_FindBySubscriberID_Call{Call: _e.mock.On("FindBySubscriberID", ctx, subscriberID)}
}

func (_c *MockEventSubscriptionRepository_FindBySubscriberID_Call) Run(run func(ctx context.Context, subscriberID string)) *MockEventSubscriptionRepository_FindBySubscriberID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_FindBySubscriberID_Call) Return(eventSubscription *domain.EventSubscription, err error) *MockEventSubscriptionRepository_FindBySubscriberID_Call {
	_c.Call.Return(eventSubscription, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_FindBySubscriberID_Call) RunAndReturn(run func(ctx context.Context, subscriberID string) (*domain.EventSubscription, error)) *MockEventSubscriptionRepository_FindBySubscriberID_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) Get(ctx context.Context, id properties.UUID) (*domain.EventSubscription, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.EventSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*domain.EventSubscription, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *domain.EventSubscription); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.EventSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEventSubscriptionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventSubscriptionRepository_Expecter) Get(ctx interface{}, id interface{}) *MockEventSubscriptionRepository_Get_Call {
	return &MockEventSubscriptionRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockEventSubscriptionRepository_Get_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventSubscriptionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_Get_Call) Return(eventSubscription *domain.EventSubscription, err error) *MockEventSubscriptionRepository_Get_Call {
	_c.Call.Return(eventSubscription, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*domain.EventSubscription, error)) *MockEventSubscriptionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.EventSubscription], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[domain.EventSubscription]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[domain.EventSubscription], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[domain.EventSubscription]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[domain.EventSubscription])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventSubscriptionRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockEventSubscriptionRepository_Expecter) List(ctx interface{}, scope interface{}, req interface{}) *MockEventSubscriptionRepository_List_Call {
	return &MockEventSubscriptionRepository_List_Call{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockEventSubscriptionRepository_List_Call) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockEventSubscriptionRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_List_Call) Return(pageRes *domain.PageRes[domain.EventSubscription], err error) *MockEventSubscriptionRepository_List_Call {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_List_Call) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.EventSubscription], error)) *MockEventSubscriptionRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListExpiredLeases provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) ListExpiredLeases(ctx context.Context) ([]*domain.EventSubscription, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListExpiredLeases")
	}

	var r0 []*domain.EventSubscription
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*domain.EventSubscription, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*domain.EventSubscription); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.EventSubscription)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventSubscriptionRepository_ListExpiredLeases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListExpiredLeases'
type MockEventSubscriptionRepository_ListExpiredLeases_Call struct {
	*mock.Call
}

// ListExpiredLeases is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventSubscriptionRepository_Expecter) ListExpiredLeases(ctx interface{}) *MockEventSubscriptionRepository_ListExpiredLeases_Call {
	return &MockEventSubscriptionRepository_ListExpiredLeases_Call{Call: _e.mock.On("ListExpiredLeases", ctx)}
}

func (_c *MockEventSubscriptionRepository_ListExpiredLeases_Call) Run(run func(ctx context.Context)) *MockEventSubscriptionRepository_ListExpiredLeases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_ListExpiredLeases_Call) Return(eventSubscriptions []*domain.EventSubscription, err error) *MockEventSubscriptionRepository_ListExpiredLeases_Call {
	_c.Call.Return(eventSubscriptions, err)
	return _c
}

func (_c *MockEventSubscriptionRepository_ListExpiredLeases_Call) RunAndReturn(run func(ctx context.Context) ([]*domain.EventSubscription, error)) *MockEventSubscriptionRepository_ListExpiredLeases_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockEventSubscriptionRepository
func (_mock *MockEventSubscriptionRepository) Save(ctx context.Context, entity *domain.EventSubscription) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.EventSubscription) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSubscriptionRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockEventSubscriptionRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.EventSubscription
func (_e *MockEventSubscriptionRepository_Expecter) Save(ctx interface{}, entity interface{}) *MockEventSubscriptionRepository_Save_Call {
	return &MockEventSubscriptionRepository_Save_Call{Call: _e.mock.On("Save", ctx, entity)}
}

func (_c *MockEventSubscriptionRepository_Save_Call) Run(run func(ctx context.Context, entity *domain.EventSubscription)) *MockEventSubscriptionRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.EventSubscription
		if args[1] != nil {
			arg1 = args[1].(*domain.EventSubscription)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventSubscriptionRepository_Save_Call) Return(err error) *MockEventSubscriptionRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSubscriptionRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entity *domain.EventSubscription) error) *MockEventSubscriptionRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
