// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockEventRepository_AuthScope_Call struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventRepository_Expecter) AuthScope(ctx interface{}, id interface{}) *MockEventRepository_AuthScope_Call {
	return &MockEventRepository_AuthScope_Call{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockEventRepository_AuthScope_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventRepository_AuthScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_AuthScope_Call) Return(objectScope auth.ObjectScope, err error) *MockEventRepository_AuthScope_Call {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockEventRepository_AuthScope_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockEventRepository_AuthScope_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockEventRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventRepository_Expecter) Count(ctx interface{}) *MockEventRepository_Count_Call {
	return &MockEventRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockEventRepository_Count_Call) Run(run func(ctx context.Context)) *MockEventRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_Count_Call) Return(n int64, err error) *MockEventRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEventRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockEventRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Create(ctx context.Context, entry *domain.Event) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Event) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *domain.Event
func (_e *MockEventRepository_Expecter) Create(ctx interface{}, entry interface{}) *MockEventRepository_Create_Call {
	return &MockEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, entry)}
}

func (_c *MockEventRepository_Create_Call) Run(run func(ctx context.Context, entry *domain.Event)) *MockEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Event
		if args[1] != nil {
			arg1 = args[1].(*domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Create_Call) Return(err error) *MockEventRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entry *domain.Event) error) *MockEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Delete(ctx context.Context, id properties.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockEventRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockEventRepository_Delete_Call {
	return &MockEventRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockEventRepository_Delete_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Delete_Call) Return(err error) *MockEventRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) error) *MockEventRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockEventRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockEventRepository_Exists_Call {
	return &MockEventRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockEventRepository_Exists_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Exists_Call) Return(b bool, err error) *MockEventRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockEventRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockEventRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Get(ctx context.Context, id properties.UUID) (*domain.Event, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*domain.Event, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *domain.Event); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockEventRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockEventRepository_Expecter) Get(ctx interface{}, id interface{}) *MockEventRepository_Get_Call {
	return &MockEventRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockEventRepository_Get_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockEventRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Get_Call) Return(event *domain.Event, err error) *MockEventRepository_Get_Call {
	_c.Call.Return(event, err)
	return _c
}

func (_c *MockEventRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*domain.Event, error)) *MockEventRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.Event], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[domain.Event]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[domain.Event], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[domain.Event]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[domain.Event])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockEventRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockEventRepository_Expecter) List(ctx interface{}, scope interface{}, req interface{}) *MockEventRepository_List_Call {
	return &MockEventRepository_List_Call{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockEventRepository_List_Call) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockEventRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_List_Call) Return(pageRes *domain.PageRes[domain.Event], err error) *MockEventRepository_List_Call {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockEventRepository_List_Call) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.Event], error)) *MockEventRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListFromSequence provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ListFromSequence(ctx context.Context, fromSequenceNumber int64, limit int) ([]*domain.Event, error) {
	ret := _mock.Called(ctx, fromSequenceNumber, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListFromSequence")
	}

	var r0 []*domain.Event
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) ([]*domain.Event, error)); ok {
		return returnFunc(ctx, fromSequenceNumber, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) []*domain.Event); ok {
		r0 = returnFunc(ctx, fromSequenceNumber, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = returnFunc(ctx, fromSequenceNumber, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_ListFromSequence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFromSequence'
type MockEventRepository_ListFromSequence_Call struct {
	*mock.Call
}

// ListFromSequence is a helper method to define mock.On call
//   - ctx context.Context
//   - fromSequenceNumber int64
//   - limit int
func (_e *MockEventRepository_Expecter) ListFromSequence(ctx interface{}, fromSequenceNumber interface{}, limit interface{}) *MockEventRepository_ListFromSequence_Call {
	return &MockEventRepository_ListFromSequence_Call{Call: _e.mock.On("ListFromSequence", ctx, fromSequenceNumber, limit)}
}

func (_c *MockEventRepository_ListFromSequence_Call) Run(run func(ctx context.Context, fromSequenceNumber int64, limit int)) *MockEventRepository_ListFromSequence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventRepository_ListFromSequence_Call) Return(events []*domain.Event, err error) *MockEventRepository_ListFromSequence_Call {
	_c.Call.Return(events, err)
	return _c
}

func (_c *MockEventRepository_ListFromSequence_Call) RunAndReturn(run func(ctx context.Context, fromSequenceNumber int64, limit int) ([]*domain.Event, error)) *MockEventRepository_ListFromSequence_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) Save(ctx context.Context, entity *domain.Event) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Event) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockEventRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.Event
func (_e *MockEventRepository_Expecter) Save(ctx interface{}, entity interface{}) *MockEventRepository_Save_Call {
	return &MockEventRepository_Save_Call{Call: _e.mock.On("Save", ctx, entity)}
}

func (_c *MockEventRepository_Save_Call) Run(run func(ctx context.Context, entity *domain.Event)) *MockEventRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Event
		if args[1] != nil {
			arg1 = args[1].(*domain.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventRepository_Save_Call) Return(err error) *MockEventRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entity *domain.Event) error) *MockEventRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// ServiceUptime provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) ServiceUptime(ctx context.Context, serviceID properties.UUID, start time.Time, end time.Time) (uint64, uint64, error) {
	ret := _mock.Called(ctx, serviceID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for ServiceUptime")
	}

	var r0 uint64
	var r1 uint64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID, time.Time, time.Time) (uint64, uint64, error)); ok {
		return returnFunc(ctx, serviceID, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID, time.Time, time.Time) uint64); ok {
		r0 = returnFunc(ctx, serviceID, start, end)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID, time.Time, time.Time) uint64); ok {
		r1 = returnFunc(ctx, serviceID, start, end)
	} else {
		r1 = ret.Get(1).(uint64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, properties.UUID, time.Time, time.Time) error); ok {
		r2 = returnFunc(ctx, serviceID, start, end)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockEventRepository_ServiceUptime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceUptime'
type MockEventRepository_ServiceUptime_Call struct {
	*mock.Call
}

// ServiceUptime is a helper method to define mock.On call
//   - ctx context.Context
//   - serviceID properties.UUID
//   - start time.Time
//   - end time.Time
func (_e *MockEventRepository_Expecter) ServiceUptime(ctx interface{}, serviceID interface{}, start interface{}, end interface{}) *MockEventRepository_ServiceUptime_Call {
	return &MockEventRepository_ServiceUptime_Call{Call: _e.mock.On("ServiceUptime", ctx, serviceID, start, end)}
}

func (_c *MockEventRepository_ServiceUptime_Call) Run(run func(ctx context.Context, serviceID properties.UUID, start time.Time, end time.Time)) *MockEventRepository_ServiceUptime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockEventRepository_ServiceUptime_Call) Return(uptimeSeconds uint64, downtimeSeconds uint64, err error) *MockEventRepository_ServiceUptime_Call {
	_c.Call.Return(uptimeSeconds, downtimeSeconds, err)
	return _c
}

func (_c *MockEventRepository_ServiceUptime_Call) RunAndReturn(run func(ctx context.Context, serviceID properties.UUID, start time.Time, end time.Time) (uint64, uint64, error)) *MockEventRepository_ServiceUptime_Call {
	_c.Call.Return(run)
	return _c
}
