// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricTypeQuerier creates a new instance of MockMetricTypeQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricTypeQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricTypeQuerier {
	mock := &MockMetricTypeQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricTypeQuerier is an autogenerated mock type for the MetricTypeQuerier type
type MockMetricTypeQuerier struct {
	mock.Mock
}

type MockMetricTypeQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricTypeQuerier) EXPECT() *MockMetricTypeQuerier_Expecter {
	return &MockMetricTypeQuerier_Expecter{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockMetricTypeQuerier
func (_mock *MockMetricTypeQuerier) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeQuerier_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockMetricTypeQuerier_AuthScope_Call struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricTypeQuerier_Expecter) AuthScope(ctx interface{}, id interface{}) *MockMetricTypeQuerier_AuthScope_Call {
	return &MockMetricTypeQuerier_AuthScope_Call{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockMetricTypeQuerier_AuthScope_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricTypeQuerier_AuthScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeQuerier_AuthScope_Call) Return(objectScope auth.ObjectScope, err error) *MockMetricTypeQuerier_AuthScope_Call {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockMetricTypeQuerier_AuthScope_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockMetricTypeQuerier_AuthScope_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockMetricTypeQuerier
func (_mock *MockMetricTypeQuerier) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeQuerier_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockMetricTypeQuerier_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetricTypeQuerier_Expecter) Count(ctx interface{}) *MockMetricTypeQuerier_Count_Call {
	return &MockMetricTypeQuerier_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockMetricTypeQuerier_Count_Call) Run(run func(ctx context.Context)) *MockMetricTypeQuerier_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricTypeQuerier_Count_Call) Return(n int64, err error) *MockMetricTypeQuerier_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMetricTypeQuerier_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockMetricTypeQuerier_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockMetricTypeQuerier
func (_mock *MockMetricTypeQuerier) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeQuerier_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMetricTypeQuerier_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricTypeQuerier_Expecter) Exists(ctx interface{}, id interface{}) *MockMetricTypeQuerier_Exists_Call {
	return &MockMetricTypeQuerier_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockMetricTypeQuerier_Exists_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricTypeQuerier_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeQuerier_Exists_Call) Return(b bool, err error) *MockMetricTypeQuerier_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMetricTypeQuerier_Exists_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockMetricTypeQuerier_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockMetricTypeQuerier
func (_mock *MockMetricTypeQuerier) FindByName(ctx context.Context, name string) (*domain.MetricType, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.MetricType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.MetricType, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.MetricType); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MetricType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeQuerier_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockMetricTypeQuerier_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMetricTypeQuerier_Expecter) FindByName(ctx interface{}, name interface{}) *MockMetricTypeQuerier_FindByName_Call {
	return &MockMetricTypeQuerier_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockMetricTypeQuerier_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockMetricTypeQuerier_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeQuerier_FindByName_Call) Return(metricType *domain.MetricType, err error) *MockMetricTypeQuerier_FindByName_Call {
	_c.Call.Return(metricType, err)
	return _c
}

func (_c *MockMetricTypeQuerier_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.MetricType, error)) *MockMetricTypeQuerier_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMetricTypeQuerier
func (_mock *MockMetricTypeQuerier) Get(ctx context.Context, id properties.UUID) (*domain.MetricType, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.MetricType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*domain.MetricType, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *domain.MetricType); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MetricType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeQuerier_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetricTypeQuerier_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricTypeQuerier_Expecter) Get(ctx interface{}, id interface{}) *MockMetricTypeQuerier_Get_Call {
	return &MockMetricTypeQuerier_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockMetricTypeQuerier_Get_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricTypeQuerier_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeQuerier_Get_Call) Return(metricType *domain.MetricType, err error) *MockMetricTypeQuerier_Get_Call {
	_c.Call.Return(metricType, err)
	return _c
}

func (_c *MockMetricTypeQuerier_Get_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*domain.MetricType, error)) *MockMetricTypeQuerier_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMetricTypeQuerier
func (_mock *MockMetricTypeQuerier) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.MetricType], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[domain.MetricType]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[domain.MetricType], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[domain.MetricType]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[domain.MetricType])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeQuerier_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMetricTypeQuerier_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockMetricTypeQuerier_Expecter) List(ctx interface{}, scope interface{}, req interface{}) *MockMetricTypeQuerier_List_Call {
	return &MockMetricTypeQuerier_List_Call{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockMetricTypeQuerier_List_Call) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockMetricTypeQuerier_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricTypeQuerier_List_Call) Return(pageRes *domain.PageRes[domain.MetricType], err error) *MockMetricTypeQuerier_List_Call {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockMetricTypeQuerier_List_Call) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.MetricType], error)) *MockMetricTypeQuerier_List_Call {
	_c.Call.Return(run)
	return _c
}
