// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricTypeRepository creates a new instance of MockMetricTypeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricTypeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricTypeRepository {
	mock := &MockMetricTypeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricTypeRepository is an autogenerated mock type for the MetricTypeRepository type
type MockMetricTypeRepository struct {
	mock.Mock
}

type MockMetricTypeRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricTypeRepository) EXPECT() *MockMetricTypeRepository_Expecter {
	return &MockMetricTypeRepository_Expecter{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeRepository_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockMetricTypeRepository_AuthScope_Call struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricTypeRepository_Expecter) AuthScope(ctx interface{}, id interface{}) *MockMetricTypeRepository_AuthScope_Call {
	return &MockMetricTypeRepository_AuthScope_Call{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockMetricTypeRepository_AuthScope_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricTypeRepository_AuthScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_AuthScope_Call) Return(objectScope auth.ObjectScope, err error) *MockMetricTypeRepository_AuthScope_Call {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockMetricTypeRepository_AuthScope_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockMetricTypeRepository_AuthScope_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockMetricTypeRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetricTypeRepository_Expecter) Count(ctx interface{}) *MockMetricTypeRepository_Count_Call {
	return &MockMetricTypeRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockMetricTypeRepository_Count_Call) Run(run func(ctx context.Context)) *MockMetricTypeRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_Count_Call) Return(n int64, err error) *MockMetricTypeRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMetricTypeRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockMetricTypeRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) Create(ctx context.Context, entity *domain.MetricType) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MetricType) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricTypeRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockMetricTypeRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.MetricType
func (_e *MockMetricTypeRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockMetricTypeRepository_Create_Call {
	return &MockMetricTypeRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockMetricTypeRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.MetricType)) *MockMetricTypeRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MetricType
		if args[1] != nil {
			arg1 = args[1].(*domain.MetricType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_Create_Call) Return(err error) *MockMetricTypeRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricTypeRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.MetricType) error) *MockMetricTypeRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) Delete(ctx context.Context, id properties.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricTypeRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockMetricTypeRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricTypeRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockMetricTypeRepository_Delete_Call {
	return &MockMetricTypeRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockMetricTypeRepository_Delete_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricTypeRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_Delete_Call) Return(err error) *MockMetricTypeRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricTypeRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) error) *MockMetricTypeRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMetricTypeRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricTypeRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockMetricTypeRepository_Exists_Call {
	return &MockMetricTypeRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockMetricTypeRepository_Exists_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricTypeRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_Exists_Call) Return(b bool, err error) *MockMetricTypeRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMetricTypeRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockMetricTypeRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// FindByName provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) FindByName(ctx context.Context, name string) (*domain.MetricType, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for FindByName")
	}

	var r0 *domain.MetricType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.MetricType, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.MetricType); ok {
		r0 = returnFunc(ctx, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MetricType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeRepository_FindByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByName'
type MockMetricTypeRepository_FindByName_Call struct {
	*mock.Call
}

// FindByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
func (_e *MockMetricTypeRepository_Expecter) FindByName(ctx interface{}, name interface{}) *MockMetricTypeRepository_FindByName_Call {
	return &MockMetricTypeRepository_FindByName_Call{Call: _e.mock.On("FindByName", ctx, name)}
}

func (_c *MockMetricTypeRepository_FindByName_Call) Run(run func(ctx context.Context, name string)) *MockMetricTypeRepository_FindByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_FindByName_Call) Return(metricType *domain.MetricType, err error) *MockMetricTypeRepository_FindByName_Call {
	_c.Call.Return(metricType, err)
	return _c
}

func (_c *MockMetricTypeRepository_FindByName_Call) RunAndReturn(run func(ctx context.Context, name string) (*domain.MetricType, error)) *MockMetricTypeRepository_FindByName_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) Get(ctx context.Context, id properties.UUID) (*domain.MetricType, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.MetricType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*domain.MetricType, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *domain.MetricType); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MetricType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetricTypeRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricTypeRepository_Expecter) Get(ctx interface{}, id interface{}) *MockMetricTypeRepository_Get_Call {
	return &MockMetricTypeRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockMetricTypeRepository_Get_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricTypeRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_Get_Call) Return(metricType *domain.MetricType, err error) *MockMetricTypeRepository_Get_Call {
	_c.Call.Return(metricType, err)
	return _c
}

func (_c *MockMetricTypeRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*domain.MetricType, error)) *MockMetricTypeRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.MetricType], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[domain.MetricType]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[domain.MetricType], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[domain.MetricType]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[domain.MetricType])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricTypeRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMetricTypeRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockMetricTypeRepository_Expecter) List(ctx interface{}, scope interface{}, req interface{}) *MockMetricTypeRepository_List_Call {
	return &MockMetricTypeRepository_List_Call{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockMetricTypeRepository_List_Call) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockMetricTypeRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_List_Call) Return(pageRes *domain.PageRes[domain.MetricType], err error) *MockMetricTypeRepository_List_Call {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockMetricTypeRepository_List_Call) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.MetricType], error)) *MockMetricTypeRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockMetricTypeRepository
func (_mock *MockMetricTypeRepository) Save(ctx context.Context, entity *domain.MetricType) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.MetricType) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetricTypeRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockMetricTypeRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.MetricType
func (_e *MockMetricTypeRepository_Expecter) Save(ctx interface{}, entity interface{}) *MockMetricTypeRepository_Save_Call {
	return &MockMetricTypeRepository_Save_Call{Call: _e.mock.On("Save", ctx, entity)}
}

func (_c *MockMetricTypeRepository_Save_Call) Run(run func(ctx context.Context, entity *domain.MetricType)) *MockMetricTypeRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.MetricType
		if args[1] != nil {
			arg1 = args[1].(*domain.MetricType)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricTypeRepository_Save_Call) Return(err error) *MockMetricTypeRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetricTypeRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entity *domain.MetricType) error) *MockMetricTypeRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
