// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetricEntryQuerier creates a new instance of MockMetricEntryQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetricEntryQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetricEntryQuerier {
	mock := &MockMetricEntryQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetricEntryQuerier is an autogenerated mock type for the MetricEntryQuerier type
type MockMetricEntryQuerier struct {
	mock.Mock
}

type MockMetricEntryQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetricEntryQuerier) EXPECT() *MockMetricEntryQuerier_Expecter {
	return &MockMetricEntryQuerier_Expecter{mock: &_m.Mock}
}

// Aggregate provides a mock function for the type MockMetricEntryQuerier
func (_mock *MockMetricEntryQuerier) Aggregate(ctx context.Context, aggregateType domain.AggregateType, serviceID properties.UUID, typeID properties.UUID, start time.Time, end time.Time) (float64, error) {
	ret := _mock.Called(ctx, aggregateType, serviceID, typeID, start, end)

	if len(ret) == 0 {
		panic("no return value specified for Aggregate")
	}

	var r0 float64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AggregateType, properties.UUID, properties.UUID, time.Time, time.Time) (float64, error)); ok {
		return returnFunc(ctx, aggregateType, serviceID, typeID, start, end)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.AggregateType, properties.UUID, properties.UUID, time.Time, time.Time) float64); ok {
		r0 = returnFunc(ctx, aggregateType, serviceID, typeID, start, end)
	} else {
		r0 = ret.Get(0).(float64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.AggregateType, properties.UUID, properties.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, aggregateType, serviceID, typeID, start, end)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricEntryQuerier_Aggregate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregate'
type MockMetricEntryQuerier_Aggregate_Call struct {
	*mock.Call
}

// Aggregate is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregateType domain.AggregateType
//   - serviceID properties.UUID
//   - typeID properties.UUID
//   - start time.Time
//   - end time.Time
func (_e *MockMetricEntryQuerier_Expecter) Aggregate(ctx interface{}, aggregateType interface{}, serviceID interface{}, typeID interface{}, start interface{}, end interface{}) *MockMetricEntryQuerier_Aggregate_Call {
	return &MockMetricEntryQuerier_Aggregate_Call{Call: _e.mock.On("Aggregate", ctx, aggregateType, serviceID, typeID, start, end)}
}

func (_c *MockMetricEntryQuerier_Aggregate_Call) Run(run func(ctx context.Context, aggregateType domain.AggregateType, serviceID properties.UUID, typeID properties.UUID, start time.Time, end time.Time)) *MockMetricEntryQuerier_Aggregate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.AggregateType
		if args[1] != nil {
			arg1 = args[1].(domain.AggregateType)
		}
		var arg2 properties.UUID
		if args[2] != nil {
			arg2 = args[2].(properties.UUID)
		}
		var arg3 properties.UUID
		if args[3] != nil {
			arg3 = args[3].(properties.UUID)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		var arg5 time.Time
		if args[5] != nil {
			arg5 = args[5].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMetricEntryQuerier_Aggregate_Call) Return(f float64, err error) *MockMetricEntryQuerier_Aggregate_Call {
	_c.Call.Return(f, err)
	return _c
}

func (_c *MockMetricEntryQuerier_Aggregate_Call) RunAndReturn(run func(ctx context.Context, aggregateType domain.AggregateType, serviceID properties.UUID, typeID properties.UUID, start time.Time, end time.Time) (float64, error)) *MockMetricEntryQuerier_Aggregate_Call {
	_c.Call.Return(run)
	return _c
}

// AuthScope provides a mock function for the type MockMetricEntryQuerier
func (_mock *MockMetricEntryQuerier) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricEntryQuerier_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockMetricEntryQuerier_AuthScope_Call struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricEntryQuerier_Expecter) AuthScope(ctx interface{}, id interface{}) *MockMetricEntryQuerier_AuthScope_Call {
	return &MockMetricEntryQuerier_AuthScope_Call{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockMetricEntryQuerier_AuthScope_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricEntryQuerier_AuthScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricEntryQuerier_AuthScope_Call) Return(objectScope auth.ObjectScope, err error) *MockMetricEntryQuerier_AuthScope_Call {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockMetricEntryQuerier_AuthScope_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockMetricEntryQuerier_AuthScope_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockMetricEntryQuerier
func (_mock *MockMetricEntryQuerier) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricEntryQuerier_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockMetricEntryQuerier_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMetricEntryQuerier_Expecter) Count(ctx interface{}) *MockMetricEntryQuerier_Count_Call {
	return &MockMetricEntryQuerier_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockMetricEntryQuerier_Count_Call) Run(run func(ctx context.Context)) *MockMetricEntryQuerier_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetricEntryQuerier_Count_Call) Return(n int64, err error) *MockMetricEntryQuerier_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMetricEntryQuerier_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockMetricEntryQuerier_Count_Call {
	_c.Call.Return(run)
	return _c
}

// CountByMetricType provides a mock function for the type MockMetricEntryQuerier
func (_mock *MockMetricEntryQuerier) CountByMetricType(ctx context.Context, typeID properties.UUID) (int64, error) {
	ret := _mock.Called(ctx, typeID)

	if len(ret) == 0 {
		panic("no return value specified for CountByMetricType")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (int64, error)); ok {
		return returnFunc(ctx, typeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) int64); ok {
		r0 = returnFunc(ctx, typeID)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, typeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricEntryQuerier_CountByMetricType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByMetricType'
type MockMetricEntryQuerier_CountByMetricType_Call struct {
	*mock.Call
}

// CountByMetricType is a helper method to define mock.On call
//   - ctx context.Context
//   - typeID properties.UUID
func (_e *MockMetricEntryQuerier_Expecter) CountByMetricType(ctx interface{}, typeID interface{}) *MockMetricEntryQuerier_CountByMetricType_Call {
	return &MockMetricEntryQuerier_CountByMetricType_Call{Call: _e.mock.On("CountByMetricType", ctx, typeID)}
}

func (_c *MockMetricEntryQuerier_CountByMetricType_Call) Run(run func(ctx context.Context, typeID properties.UUID)) *MockMetricEntryQuerier_CountByMetricType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricEntryQuerier_CountByMetricType_Call) Return(n int64, err error) *MockMetricEntryQuerier_CountByMetricType_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMetricEntryQuerier_CountByMetricType_Call) RunAndReturn(run func(ctx context.Context, typeID properties.UUID) (int64, error)) *MockMetricEntryQuerier_CountByMetricType_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockMetricEntryQuerier
func (_mock *MockMetricEntryQuerier) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricEntryQuerier_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockMetricEntryQuerier_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricEntryQuerier_Expecter) Exists(ctx interface{}, id interface{}) *MockMetricEntryQuerier_Exists_Call {
	return &MockMetricEntryQuerier_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockMetricEntryQuerier_Exists_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricEntryQuerier_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricEntryQuerier_Exists_Call) Return(b bool, err error) *MockMetricEntryQuerier_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockMetricEntryQuerier_Exists_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockMetricEntryQuerier_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockMetricEntryQuerier
func (_mock *MockMetricEntryQuerier) Get(ctx context.Context, id properties.UUID) (*domain.MetricEntry, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.MetricEntry
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*domain.MetricEntry, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *domain.MetricEntry); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MetricEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricEntryQuerier_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockMetricEntryQuerier_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockMetricEntryQuerier_Expecter) Get(ctx interface{}, id interface{}) *MockMetricEntryQuerier_Get_Call {
	return &MockMetricEntryQuerier_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockMetricEntryQuerier_Get_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockMetricEntryQuerier_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetricEntryQuerier_Get_Call) Return(metricEntry *domain.MetricEntry, err error) *MockMetricEntryQuerier_Get_Call {
	_c.Call.Return(metricEntry, err)
	return _c
}

func (_c *MockMetricEntryQuerier_Get_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*domain.MetricEntry, error)) *MockMetricEntryQuerier_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockMetricEntryQuerier
func (_mock *MockMetricEntryQuerier) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.MetricEntry], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[domain.MetricEntry]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[domain.MetricEntry], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[domain.MetricEntry]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[domain.MetricEntry])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetricEntryQuerier_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockMetricEntryQuerier_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockMetricEntryQuerier_Expecter) List(ctx interface{}, scope interface{}, req interface{}) *MockMetricEntryQuerier_List_Call {
	return &MockMetricEntryQuerier_List_Call{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockMetricEntryQuerier_List_Call) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockMetricEntryQuerier_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetricEntryQuerier_List_Call) Return(pageRes *domain.PageRes[domain.MetricEntry], err error) *MockMetricEntryQuerier_List_Call {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockMetricEntryQuerier_List_Call) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.MetricEntry], error)) *MockMetricEntryQuerier_List_Call {
	_c.Call.Return(run)
	return _c
}
