// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockParticipantRepository creates a new instance of MockParticipantRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockParticipantRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockParticipantRepository {
	mock := &MockParticipantRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockParticipantRepository is an autogenerated mock type for the ParticipantRepository type
type MockParticipantRepository struct {
	mock.Mock
}

type MockParticipantRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockParticipantRepository) EXPECT() *MockParticipantRepository_Expecter {
	return &MockParticipantRepository_Expecter{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParticipantRepository_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockParticipantRepository_AuthScope_Call struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockParticipantRepository_Expecter) AuthScope(ctx interface{}, id interface{}) *MockParticipantRepository_AuthScope_Call {
	return &MockParticipantRepository_AuthScope_Call{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockParticipantRepository_AuthScope_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockParticipantRepository_AuthScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_AuthScope_Call) Return(objectScope auth.ObjectScope, err error) *MockParticipantRepository_AuthScope_Call {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockParticipantRepository_AuthScope_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockParticipantRepository_AuthScope_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParticipantRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockParticipantRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockParticipantRepository_Expecter) Count(ctx interface{}) *MockParticipantRepository_Count_Call {
	return &MockParticipantRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockParticipantRepository_Count_Call) Run(run func(ctx context.Context)) *MockParticipantRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_Count_Call) Return(n int64, err error) *MockParticipantRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockParticipantRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockParticipantRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) Create(ctx context.Context, entity *domain.Participant) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Participant) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParticipantRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockParticipantRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.Participant
func (_e *MockParticipantRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockParticipantRepository_Create_Call {
	return &MockParticipantRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockParticipantRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.Participant)) *MockParticipantRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Participant
		if args[1] != nil {
			arg1 = args[1].(*domain.Participant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_Create_Call) Return(err error) *MockParticipantRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParticipantRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.Participant) error) *MockParticipantRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) Delete(ctx context.Context, id properties.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParticipantRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockParticipantRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockParticipantRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockParticipantRepository_Delete_Call {
	return &MockParticipantRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockParticipantRepository_Delete_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockParticipantRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_Delete_Call) Return(err error) *MockParticipantRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParticipantRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) error) *MockParticipantRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParticipantRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockParticipantRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockParticipantRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockParticipantRepository_Exists_Call {
	return &MockParticipantRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockParticipantRepository_Exists_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockParticipantRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_Exists_Call) Return(b bool, err error) *MockParticipantRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockParticipantRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockParticipantRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) Get(ctx context.Context, id properties.UUID) (*domain.Participant, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Participant
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*domain.Participant, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *domain.Participant); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Participant)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParticipantRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockParticipantRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockParticipantRepository_Expecter) Get(ctx interface{}, id interface{}) *MockParticipantRepository_Get_Call {
	return &MockParticipantRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockParticipantRepository_Get_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockParticipantRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_Get_Call) Return(participant *domain.Participant, err error) *MockParticipantRepository_Get_Call {
	_c.Call.Return(participant, err)
	return _c
}

func (_c *MockParticipantRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*domain.Participant, error)) *MockParticipantRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.Participant], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[domain.Participant]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[domain.Participant], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[domain.Participant]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[domain.Participant])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockParticipantRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockParticipantRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockParticipantRepository_Expecter) List(ctx interface{}, scope interface{}, req interface{}) *MockParticipantRepository_List_Call {
	return &MockParticipantRepository_List_Call{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockParticipantRepository_List_Call) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockParticipantRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_List_Call) Return(pageRes *domain.PageRes[domain.Participant], err error) *MockParticipantRepository_List_Call {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockParticipantRepository_List_Call) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.Participant], error)) *MockParticipantRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockParticipantRepository
func (_mock *MockParticipantRepository) Save(ctx context.Context, entity *domain.Participant) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Participant) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockParticipantRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockParticipantRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.Participant
func (_e *MockParticipantRepository_Expecter) Save(ctx interface{}, entity interface{}) *MockParticipantRepository_Save_Call {
	return &MockParticipantRepository_Save_Call{Call: _e.mock.On("Save", ctx, entity)}
}

func (_c *MockParticipantRepository_Save_Call) Run(run func(ctx context.Context, entity *domain.Participant)) *MockParticipantRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Participant
		if args[1] != nil {
			arg1 = args[1].(*domain.Participant)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockParticipantRepository_Save_Call) Return(err error) *MockParticipantRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockParticipantRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entity *domain.Participant) error) *MockParticipantRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
