// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/fulcrumproject/core/pkg/auth"
	"github.com/fulcrumproject/core/pkg/domain"
	"github.com/fulcrumproject/core/pkg/properties"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServiceGroupRepository creates a new instance of MockServiceGroupRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceGroupRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceGroupRepository {
	mock := &MockServiceGroupRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceGroupRepository is an autogenerated mock type for the ServiceGroupRepository type
type MockServiceGroupRepository struct {
	mock.Mock
}

type MockServiceGroupRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceGroupRepository) EXPECT() *MockServiceGroupRepository_Expecter {
	return &MockServiceGroupRepository_Expecter{mock: &_m.Mock}
}

// AuthScope provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) AuthScope(ctx context.Context, id properties.UUID) (auth.ObjectScope, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AuthScope")
	}

	var r0 auth.ObjectScope
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (auth.ObjectScope, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) auth.ObjectScope); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth.ObjectScope)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceGroupRepository_AuthScope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthScope'
type MockServiceGroupRepository_AuthScope_Call struct {
	*mock.Call
}

// AuthScope is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockServiceGroupRepository_Expecter) AuthScope(ctx interface{}, id interface{}) *MockServiceGroupRepository_AuthScope_Call {
	return &MockServiceGroupRepository_AuthScope_Call{Call: _e.mock.On("AuthScope", ctx, id)}
}

func (_c *MockServiceGroupRepository_AuthScope_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockServiceGroupRepository_AuthScope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_AuthScope_Call) Return(objectScope auth.ObjectScope, err error) *MockServiceGroupRepository_AuthScope_Call {
	_c.Call.Return(objectScope, err)
	return _c
}

func (_c *MockServiceGroupRepository_AuthScope_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (auth.ObjectScope, error)) *MockServiceGroupRepository_AuthScope_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) Count(ctx context.Context) (int64, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceGroupRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type MockServiceGroupRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServiceGroupRepository_Expecter) Count(ctx interface{}) *MockServiceGroupRepository_Count_Call {
	return &MockServiceGroupRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *MockServiceGroupRepository_Count_Call) Run(run func(ctx context.Context)) *MockServiceGroupRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_Count_Call) Return(n int64, err error) *MockServiceGroupRepository_Count_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockServiceGroupRepository_Count_Call) RunAndReturn(run func(ctx context.Context) (int64, error)) *MockServiceGroupRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) Create(ctx context.Context, entity *domain.ServiceGroup) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ServiceGroup) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceGroupRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServiceGroupRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.ServiceGroup
func (_e *MockServiceGroupRepository_Expecter) Create(ctx interface{}, entity interface{}) *MockServiceGroupRepository_Create_Call {
	return &MockServiceGroupRepository_Create_Call{Call: _e.mock.On("Create", ctx, entity)}
}

func (_c *MockServiceGroupRepository_Create_Call) Run(run func(ctx context.Context, entity *domain.ServiceGroup)) *MockServiceGroupRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ServiceGroup
		if args[1] != nil {
			arg1 = args[1].(*domain.ServiceGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_Create_Call) Return(err error) *MockServiceGroupRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceGroupRepository_Create_Call) RunAndReturn(run func(ctx context.Context, entity *domain.ServiceGroup) error) *MockServiceGroupRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) Delete(ctx context.Context, id properties.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceGroupRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServiceGroupRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockServiceGroupRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockServiceGroupRepository_Delete_Call {
	return &MockServiceGroupRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockServiceGroupRepository_Delete_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockServiceGroupRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_Delete_Call) Return(err error) *MockServiceGroupRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceGroupRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) error) *MockServiceGroupRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Exists provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) Exists(ctx context.Context, id properties.UUID) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Exists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceGroupRepository_Exists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exists'
type MockServiceGroupRepository_Exists_Call struct {
	*mock.Call
}

// Exists is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockServiceGroupRepository_Expecter) Exists(ctx interface{}, id interface{}) *MockServiceGroupRepository_Exists_Call {
	return &MockServiceGroupRepository_Exists_Call{Call: _e.mock.On("Exists", ctx, id)}
}

func (_c *MockServiceGroupRepository_Exists_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockServiceGroupRepository_Exists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_Exists_Call) Return(b bool, err error) *MockServiceGroupRepository_Exists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockServiceGroupRepository_Exists_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (bool, error)) *MockServiceGroupRepository_Exists_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) Get(ctx context.Context, id properties.UUID) (*domain.ServiceGroup, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.ServiceGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) (*domain.ServiceGroup, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, properties.UUID) *domain.ServiceGroup); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ServiceGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, properties.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceGroupRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockServiceGroupRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id properties.UUID
func (_e *MockServiceGroupRepository_Expecter) Get(ctx interface{}, id interface{}) *MockServiceGroupRepository_Get_Call {
	return &MockServiceGroupRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockServiceGroupRepository_Get_Call) Run(run func(ctx context.Context, id properties.UUID)) *MockServiceGroupRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 properties.UUID
		if args[1] != nil {
			arg1 = args[1].(properties.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_Get_Call) Return(serviceGroup *domain.ServiceGroup, err error) *MockServiceGroupRepository_Get_Call {
	_c.Call.Return(serviceGroup, err)
	return _c
}

func (_c *MockServiceGroupRepository_Get_Call) RunAndReturn(run func(ctx context.Context, id properties.UUID) (*domain.ServiceGroup, error)) *MockServiceGroupRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) List(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.ServiceGroup], error) {
	ret := _mock.Called(ctx, scope, req)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *domain.PageRes[domain.ServiceGroup]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) (*domain.PageRes[domain.ServiceGroup], error)); ok {
		return returnFunc(ctx, scope, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *auth.IdentityScope, *domain.PageReq) *domain.PageRes[domain.ServiceGroup]); ok {
		r0 = returnFunc(ctx, scope, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PageRes[domain.ServiceGroup])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *auth.IdentityScope, *domain.PageReq) error); ok {
		r1 = returnFunc(ctx, scope, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockServiceGroupRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServiceGroupRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - scope *auth.IdentityScope
//   - req *domain.PageReq
func (_e *MockServiceGroupRepository_Expecter) List(ctx interface{}, scope interface{}, req interface{}) *MockServiceGroupRepository_List_Call {
	return &MockServiceGroupRepository_List_Call{Call: _e.mock.On("List", ctx, scope, req)}
}

func (_c *MockServiceGroupRepository_List_Call) Run(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq)) *MockServiceGroupRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *auth.IdentityScope
		if args[1] != nil {
			arg1 = args[1].(*auth.IdentityScope)
		}
		var arg2 *domain.PageReq
		if args[2] != nil {
			arg2 = args[2].(*domain.PageReq)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_List_Call) Return(pageRes *domain.PageRes[domain.ServiceGroup], err error) *MockServiceGroupRepository_List_Call {
	_c.Call.Return(pageRes, err)
	return _c
}

func (_c *MockServiceGroupRepository_List_Call) RunAndReturn(run func(ctx context.Context, scope *auth.IdentityScope, req *domain.PageReq) (*domain.PageRes[domain.ServiceGroup], error)) *MockServiceGroupRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockServiceGroupRepository
func (_mock *MockServiceGroupRepository) Save(ctx context.Context, entity *domain.ServiceGroup) error {
	ret := _mock.Called(ctx, entity)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.ServiceGroup) error); ok {
		r0 = returnFunc(ctx, entity)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockServiceGroupRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockServiceGroupRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - entity *domain.ServiceGroup
func (_e *MockServiceGroupRepository_Expecter) Save(ctx interface{}, entity interface{}) *MockServiceGroupRepository_Save_Call {
	return &MockServiceGroupRepository_Save_Call{Call: _e.mock.On("Save", ctx, entity)}
}

func (_c *MockServiceGroupRepository_Save_Call) Run(run func(ctx context.Context, entity *domain.ServiceGroup)) *MockServiceGroupRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.ServiceGroup
		if args[1] != nil {
			arg1 = args[1].(*domain.ServiceGroup)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServiceGroupRepository_Save_Call) Return(err error) *MockServiceGroupRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockServiceGroupRepository_Save_Call) RunAndReturn(run func(ctx context.Context, entity *domain.ServiceGroup) error) *MockServiceGroupRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
